### ISSUE TITLE
Can't find this package in Sublime's Package Control

### ISSUE THREAD

**Issue by haozihong** [Exafunction/codeium-sublime#11]
No results when searching for "Codeium" in Sublime's `Package Control: Install Package` command. 

The [Codeium Sublime package page](https://packagecontrol.io/packages/Codeium) shows a status of "MISSING" because the `packages.json` file is missing.

**Comment by cccuong-jason** [comment]
I have the same issue

**Comment by Malond11** [comment]
same issue here, running latest sublime text version

**Comment by AjayAntoIsDev** [comment]
same issue

**Comment by TylersTech2020** [comment]
Same

**Comment by jfcherng** [comment]
Afaik, the only person who can resolve this is `wbond` (I don't mean to tag him here). And he is pretty busy. I mean, not very available.

**Comment by tdd3vlp** [comment]
same here

**Comment by dcs-ink** [comment]
I also came across this issue.

**Comment by LexenFairlife** [comment]
Same

**Comment by fortenforge** [comment]
Should be there now.

**Comment by LexenFairlife** [comment]
That did the trick. Thanks!
